# Generated by Django 5.1.3 on 2024-11-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroom', '0002_restroomstatus_clean_alter_restroomstatus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='restroomstatus',
            name='cleaned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restroomstatus',
            name='next_cleaning_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restroomstatus',
            name='date',
            field=models.DateField(),
        ),
    ]
